// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzmladsjrirvzzmaendi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6bWxhZHNqcmlydnp6bWFlbmRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1OTY4OTcsImV4cCI6MjA2NTE3Mjg5N30.koAb7oH2PX_RcA_tnwA3HguJmv2QvUxbBW-hpREwRqE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);